export const strings = {
  fr: {
    clockAndMoveList: 'Horloge et coups',
    opponent: 'Adversaire',
    moves: 'Coups',
    you: 'Vous',
    board: 'Échiquier',
    coachRail: 'Rail du coach',

    yourColour: 'Votre couleur',
    colorWhite: 'Blancs',
    colorBlack: 'Noirs',
    engineStrength: 'Niveau du moteur',
    timeControl: 'Cadence',
    newGame: 'Nouvelle partie',
    pause: 'Pause',
    resume: 'Reprendre',
    resign: 'Abandonner',

    tcRebuild: 'Reconstruction',
    tcPractice: 'Entraînement',
    tcTest: 'Test',
    tcBlitz: 'Blitz (mesure, n’enseigne pas)',
    tcUnlimited: 'Illimité',

    elo600: 'Découverte des pièces',
    elo800: 'Débutant',
    elo1000: 'Progression',
    elo1200: 'Novice de club',
    elo2800: 'Maître',
    eloSuffix: 'Elo',

    startingGame: 'Démarrage de la partie…',
    couldNotStartGame: 'Impossible de démarrer une partie : {message}',
    checking: 'Vérification…',
    guardUnavailable: 'Garde-fou anti-gaffe indisponible ({message}) — envoi du coup.',
    opponentThinking: 'Le moteur réfléchit…',
    moveRejected: 'Coup refusé : {message}',
    couldNotPause: 'Impossible de mettre en pause : {message}',
    pausedMessage: 'En pause — l’horloge est arrêtée. Rien ne bouge jusqu’à votre retour.',
    resignFailed: 'Échec de l’abandon : {message}',

    guardConfirmText: 'Ce coup semble perdre du matériel. Le jouer quand même, ou regarder à nouveau ?',
    lookAgain: 'Regarder à nouveau',
    playAnyway: 'Le jouer',

    resultWin: 'Vous avez gagné',
    resultLoss: 'Vous avez perdu',
    resultDraw: 'Nulle',
    resultAbandoned: 'Partie abandonnée',
    savedToJournal: 'enregistrée dans le journal',
  },
  en: {
    clockAndMoveList: 'Clock and move list',
    opponent: 'Opponent',
    moves: 'Moves',
    you: 'You',
    board: 'Board',
    coachRail: 'Coach rail',

    yourColour: 'Your colour',
    colorWhite: 'White',
    colorBlack: 'Black',
    engineStrength: 'Engine strength',
    timeControl: 'Time control',
    newGame: 'New game',
    pause: 'Pause',
    resume: 'Resume',
    resign: 'Resign',

    tcRebuild: 'Rebuild',
    tcPractice: 'Practice',
    tcTest: 'Test',
    tcBlitz: 'Blitz (measures, does not teach)',
    tcUnlimited: 'Unlimited',

    elo600: 'Learning the pieces',
    elo800: 'Beginner',
    elo1000: 'Improving',
    elo1200: 'Club novice',
    elo2800: 'Master',
    eloSuffix: 'Elo',

    startingGame: 'Starting game…',
    couldNotStartGame: 'Could not start a game: {message}',
    checking: 'Checking…',
    guardUnavailable: 'Blunder guard unavailable ({message}) — sending move.',
    opponentThinking: 'Opponent thinking…',
    moveRejected: 'Move rejected: {message}',
    couldNotPause: 'Could not pause: {message}',
    pausedMessage: 'Paused — the clock is stopped. Nothing moves until you come back.',
    resignFailed: 'Resign failed: {message}',

    guardConfirmText: 'That looks like it drops material. Play it anyway, or take another look?',
    lookAgain: 'Look again',
    playAnyway: 'Play it',

    resultWin: 'You won',
    resultLoss: 'You lost',
    resultDraw: 'Draw',
    resultAbandoned: 'Abandoned',
    savedToJournal: 'saved to the journal',
  },
};
