export const strings = {
  fr: {
    positionAria: 'Position',
    reviewAria: 'Analyse',
    timelineAria: 'Chronologie',
    firstTitle: 'Aller au début',
    prevTitle: 'Coup précédent',
    nextTitle: 'Coup suivant',
    lastTitle: 'Aller à la fin',
    downloadPgn: 'Télécharger le PGN annoté',
    accuracyHeading: 'Précision',
    movesHeading: 'Coups',
    coachTakeHeading: "L'avis du coach",
    wentWellHeading: 'Ce qui a bien fonctionné',
    secondLookHeading: 'À revoir',
    loading: 'Chargement…',
    loadError: 'Impossible de charger cette partie : {message}',
    noSummary: 'Aucune analyse disponible.',
    summaryError: 'Analyse indisponible : {message}',
    accuracyLabel: 'Précision',
    acplLabel: 'ACPL',
    nothingFlagged: "Rien à signaler pour l'instant.",
    noMistakes: 'Aucune erreur signalée — partie propre.',
    plyLabel: 'Coup {n}',
    betterLabel: 'Meilleur coup :',
    noEngineDetail: 'Pas de détail supplémentaire du moteur pour ce coup.',
  },
  en: {
    positionAria: 'Position',
    reviewAria: 'Review',
    timelineAria: 'Timeline',
    firstTitle: 'Go to start',
    prevTitle: 'Previous move',
    nextTitle: 'Next move',
    lastTitle: 'Go to end',
    downloadPgn: 'Download annotated PGN',
    accuracyHeading: 'Accuracy',
    movesHeading: 'Moves',
    coachTakeHeading: "Coach's take",
    wentWellHeading: 'What went well',
    secondLookHeading: 'Worth a second look',
    loading: 'Loading…',
    loadError: 'Could not load this game: {message}',
    noSummary: 'No summary available.',
    summaryError: 'Summary unavailable: {message}',
    accuracyLabel: 'Accuracy',
    acplLabel: 'ACPL',
    nothingFlagged: 'Nothing flagged yet.',
    noMistakes: 'No mistakes flagged — clean game.',
    plyLabel: 'Ply {n}',
    betterLabel: 'Better:',
    noEngineDetail: 'No further detail from the engine for this move.',
  },
};
