export const strings = {
  fr: {
    pageTitle: 'Aujourd’hui',
    streakLabel: 'Série de jours',
    profileHeading: 'Votre profil',
    weakestHeading: 'Motifs les plus faibles',
    stepDrills: 'Exercices',
    stepGame: 'Partie',
    stepReview: 'Analyse',
    stepDone: 'Terminé',
    stepNotYet: 'À faire',
    drillsWord: 'exercices',
    reviewedWord: 'analysée',
    notYetReviewedWord: 'pas encore analysée',
    sessionLoadError: 'Impossible de charger la session du jour : {message}',
    profileLoadError: 'Impossible de charger votre profil : {message}',
    statGamesPlayed: 'Parties jouées',
    statRatingEstimate: 'Estimation Elo',
    statAcplOverall: 'ACPL (global)',
    statAcplOpening: 'ACPL · ouverture',
    statAcplMiddlegame: 'ACPL · milieu de partie',
    statAcplEndgame: 'ACPL · finale',
    statHintsPerGame: 'Indices par partie',
    statGuardFireRate: 'Taux de déclenchement du garde-fou',
    statBlunderUnder30: 'Gaffes <30s',
    statBlunderOver120: 'Gaffes >120s',
    statDrillsDue: 'Exercices à faire',
    naCaption: 'pas encore assez de parties',
    noMotifsYet: 'Pas encore assez de parties pour identifier un point faible.',
  },
  en: {
    pageTitle: 'Today',
    streakLabel: 'Day streak',
    profileHeading: 'Your profile',
    weakestHeading: 'Weakest motifs',
    stepDrills: 'Drills',
    stepGame: 'Game',
    stepReview: 'Review',
    stepDone: 'Done',
    stepNotYet: 'Not yet',
    drillsWord: 'drills',
    reviewedWord: 'reviewed',
    notYetReviewedWord: 'not yet reviewed',
    sessionLoadError: "Could not load today's session: {message}",
    profileLoadError: 'Could not load your profile: {message}',
    statGamesPlayed: 'Games played',
    statRatingEstimate: 'Rating estimate',
    statAcplOverall: 'ACPL (overall)',
    statAcplOpening: 'ACPL · opening',
    statAcplMiddlegame: 'ACPL · middlegame',
    statAcplEndgame: 'ACPL · endgame',
    statHintsPerGame: 'Hints per game',
    statGuardFireRate: 'Guard fire rate',
    statBlunderUnder30: 'Blunders <30s',
    statBlunderOver120: 'Blunders >120s',
    statDrillsDue: 'Drills due',
    naCaption: 'not enough games yet',
    noMotifsYet: 'Not enough games yet to identify a pattern.',
  },
};
